### ISSUE TITLE
Players can't talk ingame

### ISSUE THREAD

**Issue by jinkhya** [Denis3d/Minecraft2Discord#13]
Hello, 

here's the error the console is outputting when a player tries to chat : 
https://pastebin.com/ZW099qad

You can see discord messages ingame, but impossible to chat from there.

Thanks in advance,
Jin

**Comment by Denis3d** [comment]
Hi,
You didn't give your discord bot enough permission in your discord server.
In your server go to server settings > Rôles. Select your bot name and add the manage webhook permission. Otherwise you can add the administrator permission that will give every permission to your bot.
Hopping this will resolve your issue.
Denis
PS: I will add a tutorial soon

**Comment by jinkhya** [comment]
that fixed it thank you !! keep the good work :D
