### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by IchigoGames** [Denis3d/Minecraft2Discord#36]
Not  sure how it happen but it looked like it was from this mod

Crash report https://pastebin.com/77QTFuse

Minecraft Version 1.15.2
Forge 31.1.36
minecraft2discord-1.15.2-1.1.5

**Comment by Denis3d** [comment]
net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopping(ServerLifecycleHooks.java:102)
ml.denis3d.minecraft2discord.Minecraft2Discord.onServerStop(Minecraft2Discord.java:72)
This crash has occured when the server was stopping... If the stop wasn't requested by you it think that the server was crashing and make the discord bot crash too. If I have enough time I will try to handle this error in order to make the real crash message visible

**Comment by IchigoGames** [comment]
oh ok and if i can find the  right log ill send it.

**Comment by IchigoGames** [comment]
this one just happen and may be connected https://pastebin.com/3HS11aAw

**Comment by LemADEC** [comment]
we need the full server logs, not just the crash report

**Comment by IchigoGames** [comment]
sorry forgot to close this
