### ISSUE TITLE
Crash on Server stopped

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#38]
Crashing on serverStop preventing shutdown: 

https://gist.github.com/Darkere/0f9d32dcaaa971d86f739efa0bc113c8

**Comment by IchigoGames** [comment]
for me its not crashing but its also not stopping

**Comment by Denis3d** [comment]
Can you try the jar i give to darkere on my discord (https://discord.gg/WUczf9) ?

**Comment by shadow2hel** [comment]
@Denis3d This happens because you initialize the webhookClient in the ServerChat event. So in other words, if you boot up the server with webhooks enabled and shut it down without sending any messages, it'll give you that exact error. An easy fix would be to initialize the webhookClient (if needed) somewhere in server startup.

**Comment by Denis3d** [comment]
Should be fixed in 2.0.0
