### ISSUE TITLE
[Feature Request] 1.12 to 1.13.2 Compatibility 

### ISSUE THREAD

**Issue by Jasondia16** [Denis3d/Minecraft2Discord#5]
I was thinking of having this mod compatible to version's 1.12 - 1.14.2 it'll be very cool seeing this mod in modpacks for 1.12 - 1.13.2

**Comment by Denis3d** [comment]
Thanks for the idea but I will not make this mod in 1.12.2.
Minecraft forge have been completely rewrites between 1.12.2 and 1.13. So I will need to rewrite my mod to make it in 1.12.2. But you can find another mod who have some similar fonctionnality en 1.12.
Due to forge rewrite who is very long. There is no official release for minecraft 1.13 or for minecraft 1.14 today. When rewrite will end only the last minecraft version will have a release and only this one will be used and have such mod to make a modpack. Minecraft 1.13 will not be used any more so I will not make my mod in 1.13 but the code is open source. You just have to compile the mod by yourself for 1.13-1.14 (think there is only few changement) or for 1.12 with many more changement.
Thanks for the issues and feel free to open a new one if you have more idea.
